### ISSUE TITLE
Draw player code duplicated

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#11]
https://github.com/JohnathonNow/Bending/blob/92f06d26d7b42dc77ce9a748694bc933a550e828/src/main/java/com/johnwesthoff/bending/destruct/World.java#L974-L1097

The code for drawing the player playing the game is separate from the code that draws the players they are playing with. This should not be the case.

**Comment by JohnathonNow** [comment]
In fact, a lot of code is duplicated in this way for players, and this should be sorted out.

**Comment by Wdestroier** [comment]
Hii, can you check my PR?

**Comment by JohnathonNow** [comment]
Yes, when I get a chance I will
