### ISSUE TITLE
Centralize downloaded resources

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#15]
Right now which game resources to download is scattered throughout the code. I think [ResourceManager.downloadResource](https://github.com/JohnathonNow/Bending/blob/92f06d26d7b42dc77ce9a748694bc933a550e828/src/main/java/com/johnwesthoff/bending/destruct/ResourceLoader.java#L30) shouldn't specify the full url + filename, but instead just a relative file path.

On a related note, the links to download from should probably be from GitHub for the time being. Right now it's some old webs.com link that I don't even think I have control of any more.
So, for example, https://github.com/JohnathonNow/Bending/raw/main/assets/Bending/images/AgedPaper.png should be what resource links look like.

**Comment by dkessel** [comment]
I'll try fixing this.
