### ISSUE TITLE
Reorganize code

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#2]
This codebase looks almost entirely unmaintainable, steps should be taken to improve that. There are many methods that contain far too much code, files with far too many classes, non-descriptive identifiers abound, lots of spaghetti, over 160 warnings from the linter, and more.

**Comment by pavan-kalyan** [comment]
Is there a scope defined for this? Could you also point out which modules/areas of the code need refactoring on priority?

**Comment by JohnathonNow** [comment]
Scope-wise pretty much the entire project needs varying levels of un-fubaring.
Of highest priority would be [Client.java](https://github.com/JohnathonNow/Bending/blob/main/src/main/java/com/johnwesthoff/bending/Client.java), as it is an absolute mess.
Specifically, [this networking code[(https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/Client.java#L578-L904) probably deserves its own class, and controls such as [this](https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/Client.java#L1152-L1161) and [these](https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/Client.java#L1464-L1473) should be centralized somewhere that makes sense. There's also the whole things with issues #11 and #1.

**Comment by pavan-kalyan** [comment]
Thanks for the additional info, would it make sense to have separate issues for identified areas for refactoring. So the refactoring can happen incrementally (from multiple people) rather than the entire codebase at once?

**Comment by JohnathonNow** [comment]
I suppose that is a good point. I will create the other issues.

**Comment by JohnathonNow** [comment]
Closing in favor of #1, #8, #11, #15, #23, #24, and probably some more future issues.
