### ISSUE TITLE
The Great Refactoring: Controls

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#23]
Controls such as [this](https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/Client.java#L1152-L1161), [these](https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/Client.java#L1464-L1473), and [this mess](https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/logic/ClientInputListener.java#L104-L238) should be centralized somewhere that makes sense, preferably outside of Client.

**Comment by nbrabant** [comment]
Hello! I think i can help you to refactor ;)

**Comment by JohnathonNow** [comment]
I would greatly appreciate that.
