### ISSUE TITLE
The OrderedOutputStream is probably not actually thread-safe

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#5]
https://github.com/JohnathonNow/Bending/blob/7072fc0dde7dc4978caba107b4ac306fc6ad7446/src/main/java/com/johnwesthoff/Destruct/OrderedOutputStream.java#L56-L65

This kind of locking mechanism does not prevent two threads from accessing the critical section. It should probably just be a synchronized method.

**Comment by adammcclenaghan** [comment]
@JohnathonNow Can I also propose that [this check](https://github.com/JohnathonNow/Bending/pull/9/files#diff-b517a434a3e3c7cb8394f84c74db9635R65-R67) is moved to the start of this method?

If the active flag is set to false, you will have a memory leak as you continue to add to the stack despite the run thread no longer consuming things off the stack.

**Comment by JohnathonNow** [comment]
Thanks for the contribution, and I agree with your proposal.
