### ISSUE TITLE
Magic numbers abound

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/Bending#8]
It would be nice if a lot of the magic numbers were moved to constants, especially ones reused (like the size of the screen, the framerate, etc).

**Comment by debangeedas** [comment]
Hey! I would like to give this a shot!

**Comment by JohnathonNow** [comment]
Sounds good, thanks!

**Comment by debangeedas** [comment]
I see that height, width, fps are already included in the Constants.java file. Is there anything else you would like me o add in there?

**Comment by JohnathonNow** [comment]
So there are just numbers sprinkled throughout the code, as many as can be moved out the better. Some examples:
https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/logic/Player.java#L78 looks to be some kind of walk cycle,
https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/logic/Player.java#L142 is some amount over the player to draw their health meter,
https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/logic/Player.java#L39 is the player's size, which should definitely be a constant somewhere, and
https://github.com/JohnathonNow/Bending/blob/e6dce161f3180df4a4cb19fdece6a61978cd6784/src/main/java/com/johnwesthoff/bending/logic/World.java#L110-L137 has some fluid constants with a helpful comment.
